/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface StudentProfile {
    preferredRegion: PreferredRegion;
    stream: Stream;
    interests: Array<Interest>;
    preferredCollegeType: CollegeType;
    budgetMax: bigint;
    budgetMin: bigint;
    percentage: number;
}
export interface College {
    id: bigint;
    applicationDeadline: bigint;
    latitude: number;
    stream: Stream;
    country: string;
    rankingNational: bigint;
    annualFees: bigint;
    city: string;
    name: string;
    collegeType: CollegeType;
    rankingGlobal: bigint;
    longitude: number;
    eligibilityCriteria: number;
    coursesOffered: Array<string>;
    admissionRequirements: Array<string>;
}
export interface CollegeRecommendationScore {
    matchScore: bigint;
    college: College;
}
export interface ChatMessage {
    role: Variant_bot_user;
    text: string;
    timestamp: bigint;
}
export enum CollegeType {
    deemed = "deemed",
    private_ = "private",
    government = "government"
}
export enum Interest {
    law = "law",
    arts = "arts",
    medicine = "medicine",
    engineering = "engineering",
    management = "management"
}
export enum PreferredRegion {
    uk = "uk",
    usa = "usa",
    australia = "australia",
    other = "other",
    canada = "canada",
    india = "india"
}
export enum Stream {
    arts = "arts",
    commerce = "commerce",
    science = "science"
}
export enum Variant_bot_user {
    bot = "bot",
    user = "user"
}
export interface backendInterface {
    addCollege(college: College): Promise<void>;
    addStudentProfile(profile: StudentProfile): Promise<void>;
    askChatBot(question: string): Promise<ChatMessage>;
    compareColleges(collegeIds: Array<bigint>): Promise<Array<College>>;
    getColleges(): Promise<Array<College>>;
    getRecommendations(): Promise<Array<CollegeRecommendationScore>>;
}
import type { ChatMessage as _ChatMessage, College as _College, CollegeRecommendationScore as _CollegeRecommendationScore, CollegeType as _CollegeType, Interest as _Interest, PreferredRegion as _PreferredRegion, Stream as _Stream, StudentProfile as _StudentProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCollege(arg0: College): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCollege(to_candid_College_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCollege(to_candid_College_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addStudentProfile(arg0: StudentProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addStudentProfile(to_candid_StudentProfile_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStudentProfile(to_candid_StudentProfile_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async askChatBot(arg0: string): Promise<ChatMessage> {
        if (this.processError) {
            try {
                const result = await this.actor.askChatBot(arg0);
                return from_candid_ChatMessage_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.askChatBot(arg0);
            return from_candid_ChatMessage_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async compareColleges(arg0: Array<bigint>): Promise<Array<College>> {
        if (this.processError) {
            try {
                const result = await this.actor.compareColleges(arg0);
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.compareColleges(arg0);
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getColleges(): Promise<Array<College>> {
        if (this.processError) {
            try {
                const result = await this.actor.getColleges();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getColleges();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecommendations(): Promise<Array<CollegeRecommendationScore>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecommendations();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecommendations();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ChatMessage_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChatMessage): ChatMessage {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_CollegeRecommendationScore_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CollegeRecommendationScore): CollegeRecommendationScore {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_CollegeType_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CollegeType): CollegeType {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_College_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _College): College {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Stream_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Stream): Stream {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    role: {
        bot: null;
    } | {
        user: null;
    };
    text: string;
    timestamp: bigint;
}): {
    role: Variant_bot_user;
    text: string;
    timestamp: bigint;
} {
    return {
        role: from_candid_variant_n16(_uploadFile, _downloadFile, value.role),
        text: value.text,
        timestamp: value.timestamp
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    applicationDeadline: bigint;
    latitude: number;
    stream: _Stream;
    country: string;
    rankingNational: bigint;
    annualFees: bigint;
    city: string;
    name: string;
    collegeType: _CollegeType;
    rankingGlobal: bigint;
    longitude: number;
    eligibilityCriteria: number;
    coursesOffered: Array<string>;
    admissionRequirements: Array<string>;
}): {
    id: bigint;
    applicationDeadline: bigint;
    latitude: number;
    stream: Stream;
    country: string;
    rankingNational: bigint;
    annualFees: bigint;
    city: string;
    name: string;
    collegeType: CollegeType;
    rankingGlobal: bigint;
    longitude: number;
    eligibilityCriteria: number;
    coursesOffered: Array<string>;
    admissionRequirements: Array<string>;
} {
    return {
        id: value.id,
        applicationDeadline: value.applicationDeadline,
        latitude: value.latitude,
        stream: from_candid_Stream_n20(_uploadFile, _downloadFile, value.stream),
        country: value.country,
        rankingNational: value.rankingNational,
        annualFees: value.annualFees,
        city: value.city,
        name: value.name,
        collegeType: from_candid_CollegeType_n22(_uploadFile, _downloadFile, value.collegeType),
        rankingGlobal: value.rankingGlobal,
        longitude: value.longitude,
        eligibilityCriteria: value.eligibilityCriteria,
        coursesOffered: value.coursesOffered,
        admissionRequirements: value.admissionRequirements
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    matchScore: bigint;
    college: _College;
}): {
    matchScore: bigint;
    college: College;
} {
    return {
        matchScore: value.matchScore,
        college: from_candid_College_n18(_uploadFile, _downloadFile, value.college)
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bot: null;
} | {
    user: null;
}): Variant_bot_user {
    return "bot" in value ? Variant_bot_user.bot : "user" in value ? Variant_bot_user.user : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    arts: null;
} | {
    commerce: null;
} | {
    science: null;
}): Stream {
    return "arts" in value ? Stream.arts : "commerce" in value ? Stream.commerce : "science" in value ? Stream.science : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    deemed: null;
} | {
    private: null;
} | {
    government: null;
}): CollegeType {
    return "deemed" in value ? CollegeType.deemed : "private" in value ? CollegeType.private : "government" in value ? CollegeType.government : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_College>): Array<College> {
    return value.map((x)=>from_candid_College_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CollegeRecommendationScore>): Array<CollegeRecommendationScore> {
    return value.map((x)=>from_candid_CollegeRecommendationScore_n25(_uploadFile, _downloadFile, x));
}
function to_candid_CollegeType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CollegeType): _CollegeType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_College_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: College): _College {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Interest_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Interest): _Interest {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_PreferredRegion_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PreferredRegion): _PreferredRegion {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_Stream_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Stream): _Stream {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_StudentProfile_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StudentProfile): _StudentProfile {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    applicationDeadline: bigint;
    latitude: number;
    stream: Stream;
    country: string;
    rankingNational: bigint;
    annualFees: bigint;
    city: string;
    name: string;
    collegeType: CollegeType;
    rankingGlobal: bigint;
    longitude: number;
    eligibilityCriteria: number;
    coursesOffered: Array<string>;
    admissionRequirements: Array<string>;
}): {
    id: bigint;
    applicationDeadline: bigint;
    latitude: number;
    stream: _Stream;
    country: string;
    rankingNational: bigint;
    annualFees: bigint;
    city: string;
    name: string;
    collegeType: _CollegeType;
    rankingGlobal: bigint;
    longitude: number;
    eligibilityCriteria: number;
    coursesOffered: Array<string>;
    admissionRequirements: Array<string>;
} {
    return {
        id: value.id,
        applicationDeadline: value.applicationDeadline,
        latitude: value.latitude,
        stream: to_candid_Stream_n3(_uploadFile, _downloadFile, value.stream),
        country: value.country,
        rankingNational: value.rankingNational,
        annualFees: value.annualFees,
        city: value.city,
        name: value.name,
        collegeType: to_candid_CollegeType_n5(_uploadFile, _downloadFile, value.collegeType),
        rankingGlobal: value.rankingGlobal,
        longitude: value.longitude,
        eligibilityCriteria: value.eligibilityCriteria,
        coursesOffered: value.coursesOffered,
        admissionRequirements: value.admissionRequirements
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    preferredRegion: PreferredRegion;
    stream: Stream;
    interests: Array<Interest>;
    preferredCollegeType: CollegeType;
    budgetMax: bigint;
    budgetMin: bigint;
    percentage: number;
}): {
    preferredRegion: _PreferredRegion;
    stream: _Stream;
    interests: Array<_Interest>;
    preferredCollegeType: _CollegeType;
    budgetMax: bigint;
    budgetMin: bigint;
    percentage: number;
} {
    return {
        preferredRegion: to_candid_PreferredRegion_n9(_uploadFile, _downloadFile, value.preferredRegion),
        stream: to_candid_Stream_n3(_uploadFile, _downloadFile, value.stream),
        interests: to_candid_vec_n11(_uploadFile, _downloadFile, value.interests),
        preferredCollegeType: to_candid_CollegeType_n5(_uploadFile, _downloadFile, value.preferredCollegeType),
        budgetMax: value.budgetMax,
        budgetMin: value.budgetMin,
        percentage: value.percentage
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PreferredRegion): {
    uk: null;
} | {
    usa: null;
} | {
    australia: null;
} | {
    other: null;
} | {
    canada: null;
} | {
    india: null;
} {
    return value == PreferredRegion.uk ? {
        uk: null
    } : value == PreferredRegion.usa ? {
        usa: null
    } : value == PreferredRegion.australia ? {
        australia: null
    } : value == PreferredRegion.other ? {
        other: null
    } : value == PreferredRegion.canada ? {
        canada: null
    } : value == PreferredRegion.india ? {
        india: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Interest): {
    law: null;
} | {
    arts: null;
} | {
    medicine: null;
} | {
    engineering: null;
} | {
    management: null;
} {
    return value == Interest.law ? {
        law: null
    } : value == Interest.arts ? {
        arts: null
    } : value == Interest.medicine ? {
        medicine: null
    } : value == Interest.engineering ? {
        engineering: null
    } : value == Interest.management ? {
        management: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Stream): {
    arts: null;
} | {
    commerce: null;
} | {
    science: null;
} {
    return value == Stream.arts ? {
        arts: null
    } : value == Stream.commerce ? {
        commerce: null
    } : value == Stream.science ? {
        science: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CollegeType): {
    deemed: null;
} | {
    private: null;
} | {
    government: null;
} {
    return value == CollegeType.deemed ? {
        deemed: null
    } : value == CollegeType.private ? {
        private_: null
    } : value == CollegeType.government ? {
        government: null
    } : value;
}
function to_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Interest>): Array<_Interest> {
    return value.map((x)=>to_candid_Interest_n12(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
