/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessage {
  'role' : { 'bot' : null } |
    { 'user' : null },
  'text' : string,
  'timestamp' : bigint,
}
export interface College {
  'id' : bigint,
  'applicationDeadline' : bigint,
  'latitude' : number,
  'stream' : Stream,
  'country' : string,
  'rankingNational' : bigint,
  'annualFees' : bigint,
  'city' : string,
  'name' : string,
  'collegeType' : CollegeType,
  'rankingGlobal' : bigint,
  'longitude' : number,
  'eligibilityCriteria' : number,
  'coursesOffered' : Array<string>,
  'admissionRequirements' : Array<string>,
}
export interface CollegeRecommendationScore {
  'matchScore' : bigint,
  'college' : College,
}
export type CollegeType = { 'deemed' : null } |
  { 'private' : null } |
  { 'government' : null };
export type Interest = { 'law' : null } |
  { 'arts' : null } |
  { 'medicine' : null } |
  { 'engineering' : null } |
  { 'management' : null };
export type PreferredRegion = { 'uk' : null } |
  { 'usa' : null } |
  { 'australia' : null } |
  { 'other' : null } |
  { 'canada' : null } |
  { 'india' : null };
export type Stream = { 'arts' : null } |
  { 'commerce' : null } |
  { 'science' : null };
export interface StudentProfile {
  'preferredRegion' : PreferredRegion,
  'stream' : Stream,
  'interests' : Array<Interest>,
  'preferredCollegeType' : CollegeType,
  'budgetMax' : bigint,
  'budgetMin' : bigint,
  'percentage' : number,
}
export interface _SERVICE {
  'addCollege' : ActorMethod<[College], undefined>,
  'addStudentProfile' : ActorMethod<[StudentProfile], undefined>,
  'askChatBot' : ActorMethod<[string], ChatMessage>,
  'compareColleges' : ActorMethod<[Array<bigint>], Array<College>>,
  'getColleges' : ActorMethod<[], Array<College>>,
  'getRecommendations' : ActorMethod<[], Array<CollegeRecommendationScore>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];