/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Stream = IDL.Variant({
  'arts' : IDL.Null,
  'commerce' : IDL.Null,
  'science' : IDL.Null,
});
export const CollegeType = IDL.Variant({
  'deemed' : IDL.Null,
  'private' : IDL.Null,
  'government' : IDL.Null,
});
export const College = IDL.Record({
  'id' : IDL.Nat,
  'applicationDeadline' : IDL.Int,
  'latitude' : IDL.Float64,
  'stream' : Stream,
  'country' : IDL.Text,
  'rankingNational' : IDL.Nat,
  'annualFees' : IDL.Nat,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'collegeType' : CollegeType,
  'rankingGlobal' : IDL.Nat,
  'longitude' : IDL.Float64,
  'eligibilityCriteria' : IDL.Float64,
  'coursesOffered' : IDL.Vec(IDL.Text),
  'admissionRequirements' : IDL.Vec(IDL.Text),
});
export const PreferredRegion = IDL.Variant({
  'uk' : IDL.Null,
  'usa' : IDL.Null,
  'australia' : IDL.Null,
  'other' : IDL.Null,
  'canada' : IDL.Null,
  'india' : IDL.Null,
});
export const Interest = IDL.Variant({
  'law' : IDL.Null,
  'arts' : IDL.Null,
  'medicine' : IDL.Null,
  'engineering' : IDL.Null,
  'management' : IDL.Null,
});
export const StudentProfile = IDL.Record({
  'preferredRegion' : PreferredRegion,
  'stream' : Stream,
  'interests' : IDL.Vec(Interest),
  'preferredCollegeType' : CollegeType,
  'budgetMax' : IDL.Nat,
  'budgetMin' : IDL.Nat,
  'percentage' : IDL.Float64,
});
export const ChatMessage = IDL.Record({
  'role' : IDL.Variant({ 'bot' : IDL.Null, 'user' : IDL.Null }),
  'text' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const CollegeRecommendationScore = IDL.Record({
  'matchScore' : IDL.Nat,
  'college' : College,
});

export const idlService = IDL.Service({
  'addCollege' : IDL.Func([College], [], []),
  'addStudentProfile' : IDL.Func([StudentProfile], [], []),
  'askChatBot' : IDL.Func([IDL.Text], [ChatMessage], []),
  'compareColleges' : IDL.Func(
      [IDL.Vec(IDL.Nat)],
      [IDL.Vec(College)],
      ['query'],
    ),
  'getColleges' : IDL.Func([], [IDL.Vec(College)], ['query']),
  'getRecommendations' : IDL.Func(
      [],
      [IDL.Vec(CollegeRecommendationScore)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Stream = IDL.Variant({
    'arts' : IDL.Null,
    'commerce' : IDL.Null,
    'science' : IDL.Null,
  });
  const CollegeType = IDL.Variant({
    'deemed' : IDL.Null,
    'private' : IDL.Null,
    'government' : IDL.Null,
  });
  const College = IDL.Record({
    'id' : IDL.Nat,
    'applicationDeadline' : IDL.Int,
    'latitude' : IDL.Float64,
    'stream' : Stream,
    'country' : IDL.Text,
    'rankingNational' : IDL.Nat,
    'annualFees' : IDL.Nat,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'collegeType' : CollegeType,
    'rankingGlobal' : IDL.Nat,
    'longitude' : IDL.Float64,
    'eligibilityCriteria' : IDL.Float64,
    'coursesOffered' : IDL.Vec(IDL.Text),
    'admissionRequirements' : IDL.Vec(IDL.Text),
  });
  const PreferredRegion = IDL.Variant({
    'uk' : IDL.Null,
    'usa' : IDL.Null,
    'australia' : IDL.Null,
    'other' : IDL.Null,
    'canada' : IDL.Null,
    'india' : IDL.Null,
  });
  const Interest = IDL.Variant({
    'law' : IDL.Null,
    'arts' : IDL.Null,
    'medicine' : IDL.Null,
    'engineering' : IDL.Null,
    'management' : IDL.Null,
  });
  const StudentProfile = IDL.Record({
    'preferredRegion' : PreferredRegion,
    'stream' : Stream,
    'interests' : IDL.Vec(Interest),
    'preferredCollegeType' : CollegeType,
    'budgetMax' : IDL.Nat,
    'budgetMin' : IDL.Nat,
    'percentage' : IDL.Float64,
  });
  const ChatMessage = IDL.Record({
    'role' : IDL.Variant({ 'bot' : IDL.Null, 'user' : IDL.Null }),
    'text' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const CollegeRecommendationScore = IDL.Record({
    'matchScore' : IDL.Nat,
    'college' : College,
  });
  
  return IDL.Service({
    'addCollege' : IDL.Func([College], [], []),
    'addStudentProfile' : IDL.Func([StudentProfile], [], []),
    'askChatBot' : IDL.Func([IDL.Text], [ChatMessage], []),
    'compareColleges' : IDL.Func(
        [IDL.Vec(IDL.Nat)],
        [IDL.Vec(College)],
        ['query'],
      ),
    'getColleges' : IDL.Func([], [IDL.Vec(College)], ['query']),
    'getRecommendations' : IDL.Func(
        [],
        [IDL.Vec(CollegeRecommendationScore)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };